services:
  webhook-handler:
    image: github-webhook-server:latest
    restart: always
    env_file:
      - .env.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow Flask to manage Docker containers
    ports:
      - 5001:5001
